[2022-09-21 11:14:18,319] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:14:18,319] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:14:18,324] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:14:18,324] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:14:18,324] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:14:18,324] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,513] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,513] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,516] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,516] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,516] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,516] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:35,623] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,431] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,431] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,434] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,434] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,434] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,434] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:15:53,478] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:17:31,555] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,555] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,555] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,555] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,555] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:17:31,559] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,879] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,879] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,879] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,879] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,879] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:20:39,882] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,026] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:25:48,026] - logger_.py] - ERROR: 当前请求的错误: '成功' != '用户已注册，不允许重复注册'
- 成功
+ 用户已注册，不允许重复注册

[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,723] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:25:48,725] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,554] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,554] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,562] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,562] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,562] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,562] - logger_.py] - ERROR: 当前请求的错误: Expecting value: line 1 column 1 (char 0)
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,565] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 11:39:07,575] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,108] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,108] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,108] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,108] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,108] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 16:31:36,112] - logger_.py] - ERROR: 当前请求的错误: 'Request' object has no attribute 'resp'
[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:07:51,920] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

[2022-09-21 17:11:44,427] - logger_.py] - ERROR: 当前请求的错误: '成功' != '手机号不能为空'
- 成功
+ 手机号不能为空

